---
# Ansible inventory
dns:
  hosts:
    dns0:
      ansible_host: 192.168.56.11
      ansible_user: vagrant

proxy:
  hosts:
    proxy0:
      ansible_host: 192.168.56.11
      ansible_user: vagrant

registry:
  hosts:
    registry0:
      ansible_host: 192.168.56.11
      ansible_user: vagrant

git:
  hosts:
    git0:
      ansible_host: 192.168.56.11
      ansible_user: vagrant

ci:
  hosts:
    ci0:
      ansible_host: 192.168.56.11
      ansible_user: vagrant

cluster:
  hosts:
    cp0:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
    node1:
      ansible_host: 192.168.56.13
      ansible_user: vagrant

all:
  children:
    dns:
    proxy:
    registry:
    git:
    ci:
    cluster:

